version: '2'
services:
  helloworld:
    scale: 2
    start_on_create: true
  helloworld-lb:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - hostname: localhost
        path: /
        priority: 1
        protocol: http
        service: helloworld
        source_port: 33680
        target_port: 8000
    health_check:
      response_timeout: 2000
      healthy_threshold: 2
      port: 42
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      reinitializing_timeout: 60000
